"""empty message

Revision ID: 599e4206124c
Revises: b19ad4f0971c
Create Date: 2019-12-31 09:47:56.530789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e4206124c'
down_revision = 'b19ad4f0971c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recomments', sa.Column('post_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recomments', 'post_id')
    # ### end Alembic commands ###
