"""empty message

Revision ID: 929a44e0b4fe
Revises: 26f855ce1c2f
Create Date: 2019-12-07 12:25:07.004153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929a44e0b4fe'
down_revision = '26f855ce1c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subject', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'subject')
    # ### end Alembic commands ###
