"""empty message

Revision ID: a1c702d14ec7
Revises: c56fc2c62340
Create Date: 2019-12-03 15:58:52.807257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c702d14ec7'
down_revision = 'c56fc2c62340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('password', sa.String(length=120), nullable=False))
    op.alter_column('teachers', 'avata_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('teachers', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teachers', 'avata_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('teachers', 'password')
    # ### end Alembic commands ###
