"""empty message

Revision ID: b19ad4f0971c
Revises: 3957a85cab2a
Create Date: 2019-12-27 11:08:49.367226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19ad4f0971c'
down_revision = '3957a85cab2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('readed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'readed')
    # ### end Alembic commands ###
