"""empty message

Revision ID: b9c5315cf5d8
Revises: b8bf4c206f7a
Create Date: 2019-12-20 13:29:57.323906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c5315cf5d8'
down_revision = 'b8bf4c206f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('saved', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'saved')
    # ### end Alembic commands ###
