"""empty message

Revision ID: caaaad41f706
Revises: 410ff52369b7
Create Date: 2019-12-12 22:52:49.292898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaaad41f706'
down_revision = '410ff52369b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('desc', sa.VARCHAR(length=190), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
