"""empty message

Revision ID: d953e79917ac
Revises: 10cf84071d16
Create Date: 2020-01-02 22:28:19.166980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd953e79917ac'
down_revision = '10cf84071d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'comment_id')
    # ### end Alembic commands ###
