"""empty message

Revision ID: ef9735102f85
Revises: caaaad41f706
Create Date: 2019-12-16 22:42:25.570720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9735102f85'
down_revision = 'caaaad41f706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachers_name_key', 'teachers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('teachers_name_key', 'teachers', ['name'])
    # ### end Alembic commands ###
